name: Tests

on:
  push:
    branches:
      - v5
  pull_request:
    branches:
      - v5

jobs:
  all:
    name: reporters package
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v2
      - name: Install
        shell: bash
        run: for f in $PWD/{.,assert,reporters,zora}; do cd $f && npm ci; done;
      - name: Build
        shell: bash
        run: for f in $PWD/{reporters,zora}; do cd $f && npm run build; done;
      - name: Test
        shell: bash
        run: for f in $PWD/{assert,reporters,zora}; do cd $f && npm t; done;


